# Análisis de Inscripciones Educativas

## 1. Instalación de dependencias

Dependencias necesarias para el analisis:
- Sqlalchemy
- Pandas
- Pymysql

In [3]:
%pip install sqlalchemy pymysql pandas --quiet

Note: you may need to restart the kernel to use updated packages.

## 2. Conexión a MariaDB

In [4]:
from sqlalchemy import create_engine
import pandas as pd

#Parametros para la conexión a la base de datos
DB_USER = "root"
DB_PASSWORD = "" 
DB_HOST = "127.0.0.1"
DB_PORT = 3306
DB_NAME = "inscripciones_db"

# Cadena de conexión
connection_url = (
    f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
    "?charset=utf8mb4"
)

# Creación de motor de conexión a la base de datos
engine = create_engine(connection_url, echo=False)

## 3. Carga de tablas en DataFrames

In [5]:
with engine.connect() as conn:
    df_alumnos = pd.read_sql("SELECT * FROM alumnos", conn, index_col="id")
    df_programas = pd.read_sql("SELECT * FROM programas", conn, index_col="id")
    df_inscripciones = pd.read_sql("SELECT * FROM inscripciones",    conn, index_col="id")
    df_historial_status = pd.read_sql("SELECT * FROM historial_status", conn, index_col="id")


print("── alumnos ──────────────────────────────────────────")
display(df_alumnos)

print("\n── programas ────────────────────────────────────────")
display(df_programas)

print("\n── inscripciones ────────────────────────────────────")
display(df_inscripciones)

print("\n── historial_status ─────────────────────────────────")
display(df_historial_status)

── alumnos ──────────────────────────────────────────

              nombre  empresa fecha_ingreso
id
1          Luis Cruz  Soriana    2024-02-26
2     Andrés Ramírez   Coppel    2022-10-04
3      Daniela Ortiz  Soriana    2017-10-02
4         Luis Reyes  Soriana    2015-06-06
5    Sofía Hernández  Soriana    2017-03-31
6      Paola Mendoza    Bayer    2023-03-28
7      Gabriela Cruz  Soriana    2024-03-30
8   Gabriela Morales  Soriana    2018-07-05
9        Paola López  Soriana    2017-06-01
10    Valeria Torres  Soriana    2020-11-04
11     Paola Sánchez   Alpura    2017-10-14
12    José Gutiérrez   Coppel    2022-05-06

── programas ────────────────────────────────────────

                    nombre                                        descripcion
id
1            Lic. Negocios  Licenciatura enfocada en gestión y desarrollo ...
2           Lic. Logística  Licenciatura en administración de cadenas de s...
3      Lic. Administración  Licenciatura en administración de organizacion...
4   Bachillerato Ejecutivo  Bachillerato intensivo para adultos trabajador...
5    Maestría en Dirección  Posgrado orientado al liderazgo estratégico y ...

── inscripciones ────────────────────────────────────

    id_alumno  id_programa        estatus
id
1           1            1         activo
2           2            3     suspendido
3           3            2       egresado
4           4            2       egresado
5           5            2  baja_programa
6           6            4  baja_programa
7           7            1   baja_empresa
8           8            1   baja_empresa
9           9            2       egresado
10         10            2       egresado
11         11            3      reingreso
12         12            5     suspendido

── historial_status ─────────────────────────────────

,id_inscripcion,estatus_anterior,estatus_nuevo,fecha_cambio,motivo
id,,,,,
1,1,None,inscrito,2024-02-27,Inscripción inicial al programa
2,1,inscrito,activo,2024-03-28,Inicio de actividades académicas
3,2,None,inscrito,2022-10-05,Inscripción inicial al programa
4,2,inscrito,activo,2022-11-03,Inicio de actividades académicas
5,2,activo,suspendido,2023-11-25,Adeudo pendiente de pago
6,3,None,inscrito,2017-10-03,Inscripción inicial al programa
7,3,inscrito,activo,2017-11-01,Inicio de actividades académicas
8,3,activo,egresado,2018-01-12,Cumplimiento de créditos requeridos
9,5,None,inscrito,2017-04-01,Inscripción inicial al programa
10,5,inscrito,activo,2017-04-30,Inicio de actividades académicas
11,5,activo,baja_programa,2017-09-08,Carga de trabajo elevada en empresa
12,6,None,inscrito,2023-03-29,Inscripción inicial al programa
13,6,inscrito,activo,2023-04-27,Inicio de actividades académicas
14,6,activo,baja_programa,2024-03-31,Motivos personales
15,7,None,inscrito,2024-03-31,Inscripción inicial al programa
16,7,inscrito,activo,2024-04-29,Inicio de actividades académicas
17,7,activo,baja_empresa,2025-04-26,Recorte de personal en Soriana
18,8,None,inscrito,2018-07-06,Inscripción inicial al programa
19,8,inscrito,activo,2018-08-04,Inicio de actividades académicas
20,8,activo,baja_empresa,2018-10-19,Reestructura organizacional
21,11,None,inscrito,2017-10-15,Inscripción inicial al programa
22,11,inscrito,activo,2017-11-13,Inicio de actividades académicas
23,11,activo,baja_empresa,2018-10-26,Término de contrato con Alpura
24,11,baja_empresa,reingreso,2019-02-10,Recontratación en empresa convenio
25,12,None,inscrito,2022-05-07,Inscripción inicial al programa
26,12,inscrito,activo,2022-06-05,Inicio de actividades académicas
27,12,activo,suspendido,2023-07-02,Pausa temporal por situación laboral